set-option -sa terminal-overrides ",xterm-256color:RGB"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tbfox/tmux-gruvbox'

set -g @tmux-gruvbox 'dark'
set -g @tmux-gruvbox-zoom-color 'true'

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g default-terminal "tmux-256color"
set -g mouse on

source-file ~/.config/tmux/windows.tmux
source-file ~/.config/tmux/statusbar.tmux
source-file ~/.config/tmux/copy-mode.tmux
source-file ~/.config/tmux/nvim-navigator.tmux
source-file ~/.config/tmux/new-pane-current-path.tmux

run '~/.tmux/plugins/tpm/tpm'
run '~/.tmux/plugins/tmux-gruvbox/gruvbox-tpm.tmux'
